### ISSUE TITLE
[Question] PCB Housing 

### ISSUE THREAD

**Issue by vr-hunter** [Mat931/esp32-doorbell-bus-interface#5]
Hey @Mat931, thanks again for this awesome project! Mine is working nicely so far!

Since my PCB is currently dangling from the bus lines, I was wondering if you chose the PCB with an existing housing in mind? 
If not, would it be possible to share the 3D model as a step file?

**Comment by Mat931** [comment]
Hi @vr-hunter!
I designed the board so it can fit in a 60mm diameter circle (flush mounted wall box) with not much room to spare. If you need a 3D model of the board you can import the PCB file into EasyEDA and export an OBJ file from there.

**Comment by vr-hunter** [comment]
Gotcha, I'll try and export it from there. If I can find some time for it, I'll probably design a small wall-mountable enclosure.
