### ISSUE TITLE
Spare PCBs

### ISSUE THREAD

**Issue by oskarn97** [Mat931/esp32-doorbell-bus-interface#8]
Hey Mat! 

Very cool project - I have created a similar device for another manufacturer and now switched flats - the new system is Busch Jäger Welcome. I was wondering if you still have a spare assembled version at hand. Would love to support your work.

Oskar

**Comment by oskarn97** [comment]
Thanks for the reply Mat - no worries, will order it from JLC then. Well done, again!

**Comment by Pixelramp** [comment]
> Thanks for the reply Mat - no worries, will order it from JLC then. Well done, again!

Sorry for opening this again, did you order a PCB and got one left for me?

**Comment by Mat931** [comment]
@oskarn97 Still no. But maybe you can organize a group order with someone else like it was done recently.

**Comment by oskarn97** [comment]
I have one left as I had to order two - you can write me on Reddit u/oskarn97

**Comment by oskarn97** [comment]
@Pixelramp do you still want one? You didn't reply to my message in reddit.

**Comment by Pixelramp** [comment]
@oskarn97 Hey, sorry for the late reply! I’ve got some coming from JLCPCB. A neighbor also wants the PCB.
